PRAGMA foreign_keys = off;
BEGIN TRANSACTION

DROP TABLE IF EXISTS product;
CREATE TABLE product (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, product_type VARCHAR (32), name VARCHAR (255), category_id INTEGER, price VARCHAR (32), desc VARCHAR (255), img VARCHAR (255))

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;